[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.?venv
  | \.direnv
  | _build
  | buck-out
  | build
  | dist
)
'''

[tool.pytest-watcher]
now = true
clear = true
delay = 0.2
runner = "pytest"
runner_args = ["-Werror", "-vv"]
patterns = ["broker/*.py", "tests/*.py"]
ignore_patterns = ["venv/*", ".venv/*"]
