---
applications:
- name: ((APP_NAME))
  memory: 256M
  instances: 3
  command: /app/scripts/run-app
  services:
  - ((DB_NAME))
  - ((REDIS_NAME))
  buildpacks:
  - python_buildpack
  env:
    FLASK_ENV: ((FLASK_ENV))
    BROKER_USERNAME: ((BROKER_AUTH_USERNAME))
    BROKER_PASSWORD: ((BROKER_AUTH_PASSWORD))
    SECRET_KEY: ((FLASK_SECRET_KEY))
