---
applications:
- name: ((APP_NAME))
  memory: 256M
  instances: 1
  command: gunicorn -b 0.0.0.0:$PORT 'broker.app:create_app()'
  services:
  - ((DB_NAME))
  buildpacks:
  - python_buildpack
  env:
    FLASK_ENV: ((FLASK_ENV))
    DATABASE_ENCRYPTION_KEY: ((DATABASE_ENCRYPTION_KEY))
    ALB_LISTENER_ARNS: ((ALB_LISTENER_ARNS))
    AWS_GOVCLOUD_REGION: ((AWS_GOVCLOUD_REGION))
    AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((AWS_GOVCLOUD_SECRET_ACCESS_KEY))
    AWS_GOVCLOUD_ACCESS_KEY_ID: ((AWS_GOVCLOUD_ACCESS_KEY_ID))
