version: '3'
services:
  postgresql:
    build:
      context: ./postgresql
      args:
        - USER=${USER}
    container_name: postgresql
    volumes:
      - ./postgresql/pg_hba.conf:/tmp/data/pg_hba.conf
    ports:
      - 5432:5432
    expose:
      - "5432"