jobs:

- name: reconfigure
  plan:
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version of
    # the credentials file.
    trigger: false
  - get: src
    params: {depth: 1}
    trigger: true
  - set_pipeline: domain-broker
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [reconfigure]

  - put: dev-docker-image
    params:
      build: src/docker
      tag_as_latest: true
      target: dev
      cache: true
      get_params:
        skip_download: true

  - task: test
    image: dev-docker-image
    config:
      platform: linux
      run:
        path: docker/run_tests

resources:

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: dev-docker-image
  type: docker-image
  icon: docker
  source: &docker-image-params
    repository: ((dev-docker-image))
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
