jobs:

- name: reconfigure
  plan:
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version of
    # the credentials file.
    trigger: false
  - get: src
    trigger: true
  - set_pipeline: domain-broker
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
  - get: src
    trigger: true
    passed: [reconfigure]
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 18fgsa/concourse-task
      inputs:
      - name: src
      run:
        path: src/test

resources:

- name: secrets
  type: s3-iam
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
