jobs:

- name: reconfigure
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version
    # of the credentials file.
    trigger: false
  - set_pipeline: domain-broker
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [reconfigure]

  - put: dev-docker-image
    params:
      build: src
      dockerfile: src/docker/Dockerfile
      tag_as_latest: true
      target_name: dev
      cache: true

  - task: test
    # Run the tests using the image pushed above.
    image: dev-docker-image
    config:
      platform: linux
      run:
        path: /app/docker/run_tests

- name: release
  # Better would be to tag this as candidate, and upgrade to latest later
  # in the pipeline.
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [test]

  - put: docker-image
    params:
      build: src
      dockerfile: src/docker/Dockerfile
      tag_as_latest: true
      target_name: prod
      cache: true

- name: deploy-dev
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [release]
  - put: cf-dev
    params:
      manifest: src/manifest.yml
      current_app_name: domain-broker
      show_app_log: true
      vars:
        docker-image: ((release-docker-image))

resources:

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: dev-docker-image
  type: docker-image
  icon: docker
  source: &docker-image-params
    repository: ((docker-image-dev))
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))

- name: docker-image
  type: docker-image
  icon: docker
  source:
    <<: *docker-image-params
    repository: ((docker-image-release))

- name: cf-dev
  type: cf
  icon: cloud-upload
  source:
    api: ((dev-cf-api-url))
    username: ((dev-cf-username))
    password: ((dev-cf-password))
    organization: ((dev-cf-organization))
    space: ((dev-cf-space))

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
